# Generated by Django 4.2.3 on 2023-07-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrelas'), ('GALAXIA', 'Galaxias'), ('PLANETA', 'Planetas')], default='', max_length=100),
        ),
    ]
